In [1]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
matchupsData=pd.read_csv(r"C:\Users\ttjrb\OneDrive\Desktop\University Important\summer 2024 work\projects\databases\ALL 1320 nba games 2022-23\matchups.csv")

In [2]:
matchupsData.head()

,gameid,home,ofid,ofplayer,ofteam,deid,deplayer,deteam,matchupSEC,partialPOS,...,matchup3PM,matchup3PA,matchup3Ppct,helpBLK,helpFGM,helpFGA,helpFGpct,matchupFTM,matchupFTA,shootingfouls
0,22200001,True,1627759,Jaylen Brown,BOS,203954,Joel Embiid,PHI,38.3,4.3,...,0,0,0.0,0,0,0,0,0,0,0
1,22200001,True,1627759,Jaylen Brown,BOS,201935,James Harden,PHI,78.2,7.3,...,0,2,0.0,0,0,0,0,0,0,0
2,22200001,True,1627759,Jaylen Brown,BOS,1626149,Montrezl Harrell,PHI,12.7,2.1,...,0,1,0.0,0,0,0,0,0,0,0
3,22200001,True,1627759,Jaylen Brown,BOS,202699,Tobias Harris,PHI,479.8,38.0,...,0,1,0.0,0,0,0,0,0,0,0
4,22200001,True,1627759,Jaylen Brown,BOS,1627863,Danuel House Jr.,PHI,57.7,4.3,...,1,2,0.5,0,0,0,0,0,0,0

In [3]:
#create an empty dataframe with the desired columns
df=pd.DataFrame(columns=['name','matchup','time','pts'])

In [4]:
#extract the list of unique players that played during this season
players= matchupsData['ofplayer'].unique()
i=0

#iterating every player and isolationg all their matchups data in a new data frame
for player in players:
    playerLoc= matchupsData[matchupsData['ofplayer']==player]

#extract the list of unique players the actual player (iteration) had a matchup against
    playerMatchups= playerLoc['deplayer'].unique()

#iterating every player from the matchups list and finding the sum of the matchup time and of the points scored
    for matchup in playerMatchups:
        matchupTime= playerLoc[playerLoc['deplayer']==matchup]['matchupSEC'].sum()
        matchupPts= playerLoc[playerLoc['deplayer']==matchup]['playerPTS'].sum()

#appending each matchup total stats to the pre-created dataframe
        df.loc[i]=[player,matchup,matchupTime,matchupPts]
        i+=1

In [5]:
df

                    name                   matchup    time  pts
0           Jaylen Brown               Joel Embiid   464.8   25
1           Jaylen Brown              James Harden  1391.1   40
2           Jaylen Brown          Montrezl Harrell    17.9    2
3           Jaylen Brown             Tobias Harris  2167.5   38
4           Jaylen Brown          Danuel House Jr.   121.9    5
...                  ...                       ...     ...  ...
136136  Tristan Thompson                Jeff Green    38.9    0
136137  Tristan Thompson              Jamal Murray    56.5    2
136138  Tristan Thompson        Michael Porter Jr.    18.7    0
136139  Tristan Thompson  Kentavious Caldwell-Pope    16.8    0
136140  Tristan Thompson              Aaron Gordon    41.0    0

[136141 rows x 4 columns]

In [6]:
df.sort_values('pts',ascending=False)

                    name            matchup    time  pts
3858         Joel Embiid         Al Horford  3762.0  122
40567        Bam Adebayo        Brook Lopez  3994.6  108
79347       Nikola Jokic      Deandre Ayton  3163.7  108
10833      Anthony Davis       Nikola Jokic  3724.1   99
39855       Jimmy Butler       Jrue Holiday  4150.7   97
...                  ...                ...     ...  ...
76672           Rudy Gay  Marvin Bagley III    42.8    0
76671           Rudy Gay        Isaac Okoro    25.5    0
76670           Rudy Gay        Evan Mobley    62.5    0
76668           Rudy Gay         Kevin Love   210.0    0
136140  Tristan Thompson       Aaron Gordon    41.0    0

[136141 rows x 4 columns]

In [7]:
df.sort_values('time',ascending=False).to_csv("most recurrent matchups (from prompt7).csv",index=False)