In [46]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
matchupsData=pd.read_csv(r"C:\Users\ttjrb\OneDrive\Desktop\University Important\summer 2024 work\projects\databases\ALL 1320 nba games 2022-23\matchups.csv")

In [47]:
matchupsData.head()

,gameid,home,ofid,ofplayer,ofteam,deid,deplayer,deteam,matchupSEC,partialPOS,...,matchup3PM,matchup3PA,matchup3Ppct,helpBLK,helpFGM,helpFGA,helpFGpct,matchupFTM,matchupFTA,shootingfouls
0,22200001,True,1627759,Jaylen Brown,BOS,203954,Joel Embiid,PHI,38.3,4.3,...,0,0,0.0,0,0,0,0,0,0,0
1,22200001,True,1627759,Jaylen Brown,BOS,201935,James Harden,PHI,78.2,7.3,...,0,2,0.0,0,0,0,0,0,0,0
2,22200001,True,1627759,Jaylen Brown,BOS,1626149,Montrezl Harrell,PHI,12.7,2.1,...,0,1,0.0,0,0,0,0,0,0,0
3,22200001,True,1627759,Jaylen Brown,BOS,202699,Tobias Harris,PHI,479.8,38.0,...,0,1,0.0,0,0,0,0,0,0,0
4,22200001,True,1627759,Jaylen Brown,BOS,1627863,Danuel House Jr.,PHI,57.7,4.3,...,1,2,0.5,0,0,0,0,0,0,0

In [48]:
matchupsData.shape

(243776, 33)

In [49]:
len(matchupsData[matchupsData['ofplayer']=='Jaylen Brown'])

811

In [50]:
brown=matchupsData[matchupsData['ofplayer']=='Jaylen Brown']

brown[brown['deplayer']=='Joel Embiid']['matchupSEC'].sum()

464.8

In [51]:
df=pd.DataFrame(columns=['name','matchup','time','pts'])

In [56]:
brownMatchups= brown['deplayer'].unique()

for i,matchup in enumerate(brownMatchups,0):
    matchupTime= brown[brown['deplayer']==matchup]['matchupSEC'].sum()
    matchupPts= brown[brown['deplayer']==matchup]['playerPTS'].sum()

    df.loc[i]=['Jaylen Brown',matchup,matchupTime,matchupPts]

In [70]:
df.sort_values('time',ascending=False)

             name              matchup    time  pts
3    Jaylen Brown        Tobias Harris  2167.5   38
10   Jaylen Brown         Jimmy Butler  2102.6   28
111  Jaylen Brown      Dejounte Murray  1969.5   32
8    Jaylen Brown          P.J. Tucker  1855.8   49
30   Jaylen Brown          Ayo Dosunmu  1850.1   36
..            ...                  ...     ...  ...
327  Jaylen Brown    Julian Champagnie     1.4    1
334  Jaylen Brown         Luka Samanic     1.4    0
257  Jaylen Brown       Charles Bassey     1.4    0
271  Jaylen Brown        Malachi Flynn     1.4    0
272  Jaylen Brown  Juancho Hernangomez     1.4    0

[341 rows x 4 columns]